### ISSUE TITLE
Continuing forking and contributing

### ISSUE THREAD

**Issue by hleb-kastseika** [poi519/50-bit-grayscale#1]
I accidentally found your game, tried it and I liked it! 
Also I forked it because I'd like to work with it - investigate your code, possible modify and improve (if I'll be able:). And I'd like to know your opinion about this, because I didn't found which license you use and how you want to provide your work.

**Comment by poi519** [comment]
You can do whatever you want license:)

Я писал ее для конкурса /gd/ когда-то давно, форкай, контрибьють, спрашивай.

> Среда, 25 ноября 2015, 7:47 -08:00 от last-khajiit notifications@github.com:
> 
> I accidentally found your game, tried it and I liked it! 
> Also I forked it because I'd like to work with it - investigate your code, possible modify and improve (if I'll be able:). And I'd like to know your opinion about this, because I didn't found which license you use and how you want to provide your work.
> —
> Reply to this email directly or  view it on GitHub .

## 

аофлда аолфдао

**Comment by hleb-kastseika** [comment]
Просто подумал, что это не очень вежливо будет юзать чужой код с неизвестной лицензией, поэтому решил уточнить. 
Ишью можно закрыть наверн, я узнал, что хотел, спасибо!
